import { afterAll, describe, expect, test } from 'bun:test'
import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { parseLatex, type Block } from '../latex/parse.ts'
import { hashesOf, listPapers, readPaper } from '../store.ts'

/**
 * `\input` inside an included file, followed.
 *
 * The thesis's Results chapter `\input`s two generated tables and a list of
 * quotations, and its appendices `\input` the codebook and the protocol. The
 * walk used to stop one level down, so all five were missing from the reading
 * view and every table after the first two was numbered two lower than the
 * PDF. This fixture is that shape, small: a chapter that `\input`s a table
 * from `generated/` with and without `.tex`, a cycle, a climb out of the root,
 * a target that is not there, and an `\IfFileExists` whose file is absent.
 */
const root = realpathSync(mkdtempSync(join(tmpdir(), 'kehikko-paper-nested-')))
afterAll(() => rmSync(root, { recursive: true, force: true }))

const paper = join(root, '.kehikot', 'paper', 'thesis')
mkdirSync(join(paper, 'chapters'), { recursive: true })
mkdirSync(join(paper, 'generated'), { recursive: true })
/* Something outside the paper's root that a climbing `\input` would reach. */
writeFileSync(join(root, '.kehikot', 'outside.tex'), '\\section{Not the paper}\nA secret sentence.\n')

const TABLE = (label: string, caption: string) =>
  [
    '% Generated by a script; do not edit by hand.',
    '\\begin{table}[ht]',
    '\\centering',
    `\\caption{${caption}}`,
    `\\label{${label}}`,
    '\\begin{tabular}{>{\\raggedright\\arraybackslash}p{3.0cm}rr >{\\raggedright\\arraybackslash}p{5.7cm}}',
    '\\hline',
    ' & Vanilla & Post- & \\\\',
    'Category & JS & query & Extract \\\\',
    '\\hline',
    'Positive & 46 & 14 & ``It was fun.\'\' [vanilla JS, 5] \\\\',
    'Negative & 2 & 6 & -- \\\\',
    '\\hline',
    '\\end{tabular}',
    '\\end{table}',
  ].join('\n')

writeFileSync(
  join(paper, 'main.tex'),
  [
    '\\documentclass{report}',
    '\\begin{document}',
    '\\chapter{Methods}',
    '\\begin{table}\\caption{First.}\\label{tab:first}\\begin{tabular}{ll}a & b \\\\\\end{tabular}\\end{table}',
    '\\include{chapters/results}',
    '\\include{chapters/appendix}',
    '\\end{document}',
  ].join('\n'),
)
writeFileSync(
  join(paper, 'chapters', 'results.tex'),
  [
    '\\chapter{Results}',
    'Table~\\ref{tab:cats} and Table~\\ref{tab:joint} come from the sheet; Table~\\ref{tab:after} after them.',
    '',
    '\\input{generated/tab_cats}',
    '\\input{generated/tab_joint.tex}',
    '',
    '\\paragraph{Extracts.}',
    'The extracts below.',
    '\\input{generated/quotes}',
    '',
    '\\begin{table}\\caption{After.}\\label{tab:after}\\begin{tabular}{ll}a & b \\\\\\end{tabular}\\end{table}',
  ].join('\n'),
)
writeFileSync(join(paper, 'generated', 'tab_cats.tex'), TABLE('tab:cats', 'Categories.'))
writeFileSync(join(paper, 'generated', 'tab_joint.tex'), TABLE('tab:joint', 'Joint display.'))
writeFileSync(
  join(paper, 'generated', 'quotes.tex'),
  ['\\begin{itemize}', '  \\item One quote.', '  \\item Another quote.', '\\end{itemize}', '\\input{generated/loop}'].join('\n'),
)
/* A cycle two files long: quotes → loop → quotes. */
writeFileSync(join(paper, 'generated', 'loop.tex'), 'Looped once.\n\n\\input{generated/quotes}\n')
writeFileSync(
  join(paper, 'chapters', 'appendix.tex'),
  [
    '\\chapter{Coding protocol}',
    '\\input{generated/protocol}',
    '\\IfFileExists{generated/recode.tex}{\\section{Stability check}\\input{generated/recode}}{}',
    '\\IfFileExists{generated/protocol.tex}{\\section{Protocol present}}{\\section{Protocol absent}}',
    '\\input{../../outside}',
    '\\input{generated/not_yet}',
  ].join('\n'),
)
writeFileSync(join(paper, 'generated', 'protocol.tex'), '\\subsection*{Corpus}\nThe corpus is the free text.\n')

const read = () => readPaper('thesis', root)!
const text = (b: Block) =>
  'segments' in b ? b.segments.map((s) => s.text).join('') : 'raw' in b ? b.raw : ''
const everything = () => read().blocks.map(text).join('\n')

describe('an \\input inside an included chapter', () => {
  test('is followed in place, with and without .tex', () => {
    const { blocks, files } = read()
    expect(files).toContain('generated/tab_cats.tex')
    expect(files).toContain('generated/tab_joint.tex')
    const order = blocks.filter((b) => b.kind === 'table').map((b) => (b as { label?: string }).label)
    expect(order).toEqual(['tab:first', 'tab:cats', 'tab:joint', 'tab:after'])
  })

  test('nests: a file reached through two levels of \\input is still placed', () => {
    const quotes = read().blocks.find((b) => b.kind === 'list')
    expect(quotes?.file).toBe('generated/quotes.tex')
    expect(read().blocks.some((b) => b.file === 'generated/loop.tex' && text(b).includes('Looped once'))).toBe(true)
  })

  test('every expanded block carries the file it came from and that file’s own offsets', () => {
    const { blocks } = read()
    const table = blocks.find((b) => b.kind === 'table' && b.label === 'tab:cats')!
    expect(table.file).toBe('generated/tab_cats.tex')
    /* The table opens after the one comment line of its own file — not at an
       offset somewhere inside the chapter that named it. */
    const source = '% Generated by a script; do not edit by hand.\n'
    expect(table.srcStart).toBe(Buffer.byteLength(source))
    /* And the chapter's own blocks keep the chapter. */
    const prose = blocks.find((b) => b.kind === 'paragraph' && text(b).includes('come from the sheet'))!
    expect(prose.file).toBe('chapters/results.tex')
  })

  test('labels resolve across the \\input, and the numbering counts the tables it brought', () => {
    const prose = read().blocks.find((b) => b.kind === 'paragraph' && text(b).includes('come from the sheet'))!
    expect(text(prose)).toContain('Table 2.1 and Table 2.2')
    expect(text(prose)).toContain('Table 2.3 after them')
    expect(everything()).not.toContain('§tab:')
  })

  test('a cycle is refused visibly rather than followed forever', () => {
    const refusal = read().blocks.find((b) => b.kind === 'unknown' && text(b).startsWith('\\input{generated/quotes}'))
    expect(refusal?.file).toBe('generated/loop.tex')
    expect(text(refusal!)).toContain('go round forever')
  })

  test('a target that climbs out of the paper’s root reads nothing, and says so', () => {
    expect(everything()).not.toContain('A secret sentence')
    const refusal = read().blocks.find((b) => b.kind === 'unknown' && text(b).startsWith('\\input{../../outside}'))
    expect(refusal?.file).toBe('chapters/appendix.tex')
  })

  test('a missing target is a visible block in the words the author wrote', () => {
    const missing = read().blocks.find((b) => b.kind === 'unknown' && text(b).startsWith('\\input{generated/not_yet}'))
    expect(text(missing!)).toContain('not on disk here')
  })

  test('\\IfFileExists takes the false branch for a file that is not there, and produces nothing and no error', () => {
    const all = everything()
    expect(all).not.toContain('Stability check')
    expect(all).not.toContain('recode')
    expect(read().files).not.toContain('generated/recode.tex')
  })

  test('\\IfFileExists takes the true branch for a file that is there', () => {
    const headings = read().blocks.filter((b) => b.kind === 'heading').map(text)
    expect(headings).toContain('Protocol present')
    expect(headings).not.toContain('Protocol absent')
  })

  test('the hashes and the list see the same files the read opened', () => {
    expect(Object.keys(hashesOf('thesis', root)!).sort()).toEqual([...read().files].sort())
    expect(listPapers(root).find((p) => p.epic === 'thesis')?.files).toBe(read().files.length)
  })
})

describe('the parser on its own', () => {
  test('\\IfFileExists asks the caller, and parses the chosen branch at its own offsets', () => {
    const src = '\\begin{document}\n\\IfFileExists{x.tex}{\\section{Yes}}{\\section{No}}\n\\end{document}'
    const yes = parseLatex(src, 'a.tex', undefined, () => true).blocks.filter((b) => b.kind === 'heading')
    const no = parseLatex(src, 'a.tex').blocks.filter((b) => b.kind === 'heading')
    expect(yes.map(text)).toEqual(['Yes'])
    expect(no.map(text)).toEqual(['No'])
    expect(no[0]!.srcStart).toBe(src.indexOf('\\section{No}'))
  })

  test('a line starting with \\IfFileExists ends the paragraph above it', () => {
    const src = '\\begin{document}\nSome prose.\n\\IfFileExists{x}{}{}\n\\end{document}'
    const paragraphs = parseLatex(src, 'a.tex').blocks.filter((b) => b.kind === 'paragraph')
    expect(paragraphs.map(text)).toEqual(['Some prose.'])
  })

  test('an include block records which command it was', () => {
    const [block] = parseLatex('\\input{generated/x}', 'a.tex').blocks
    expect(block).toMatchObject({ kind: 'include', command: 'input', target: 'generated/x' })
  })
})

describe('a generated table with >{\\raggedright\\arraybackslash}p{…} columns and a two-row header', () => {
  const grid = () => {
    const table = parseLatex(TABLE('tab:j', 'J.'), 'generated/t.tex').blocks.find((b) => b.kind === 'table')
    if (!table || table.kind !== 'table' || !table.grid) throw new Error('no grid')
    return table.grid
  }

  test('reads four columns: the >{…} insert is not a column of its own', () => {
    for (const row of grid().rows) expect(row.cells.reduce((n, c) => n + c.colSpan, 0)).toBe(4)
    expect(grid().rows[2]!.cells.map((c) => c.align)).toEqual(['left', 'right', 'right', 'left'])
  })

  test('both header rows are headers and the body rows are not', () => {
    expect(grid().rows.map((r) => r.isHeader)).toEqual([true, true, false, false])
    expect(grid().rows[1]!.cells.map((c) => c.segments.map((s) => s.text).join('').trim())).toEqual([
      'Category',
      'JS',
      'query',
      'Extract',
    ])
  })

  test('a cell keeps its prose, quotes and all', () => {
    const extract = grid().rows[2]!.cells[3]!.segments.map((s) => s.text).join('')
    expect(extract).toContain('It was fun.')
    expect(grid().ruleBelow).toBe(true)
  })
})
